### ISSUE TITLE
Error: [object Object]

### ISSUE THREAD

**Issue by brunomosciatti** [rufuspollock/s3-bucket-listing#84] opened 2019-01-28 17:10 UTC
I want to list everything from  https://astralcultural.s3.amazonaws.com/capas/marketplace

But all I got is this error message:
Error: [object Object]

`<!DOCTYPE html>
<html>
<head>
  <title>S3 Bucket Listing Generator</title>
</head>
<body>
  <div id="navigation"></div>
  <div id="listing"></div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
   var S3BL_IGNORE_PATH = true;
   var BUCKET_NAME = 'astralcultural.com.br';
   var BUCKET_URL = 'https://astralcultural.s3.amazonaws.com';
   var S3B_ROOT_DIR = 'capas/marketplace/';
   var S3B_SORT = 'DEFAULT';
   var EXCLUDE_FILE = 'index.html';  // change to array to exclude multiple files
   var AUTO_TITLE = true;
   var S3_REGION = 's3'; // for us-east-1
</script>
<script type="text/javascript" src="https://rawgit.com/rufuspollock/s3-bucket-listing/gh-pages/list.js"></script>
</body>
</html>
`

**Comment by rufuspollock** [comment] 2019-01-31 19:03
What is error details?

**Comment by jmukhtar** [comment] 2019-02-25 14:05
Hi, I am getting the same error.

In console, i am getting 403 Forbidden when calling in the http://BUCKET_URL/?delimiter=/

We have not made the bucket public but have bucket policy allowing access from specific IP addresses.

Any idea what could be the reason. I can successfully get to index.html and it downloads list.js but then after that it shows forbidden error

**Comment by mattnewark** [comment] 2019-03-01 10:11
Hi, Can see this is being caused by a CORS error in my case as I am sending the request from localhost.  Is this normal behavior and have you an idea of how I am able to resolve this issue

**Comment by rufuspollock** [comment] 2019-03-20 20:59
@mattnewark yes it will be normal if you don't have cors turned on in those buckets.

**Comment by rufuspollock** [comment] 2019-03-20 20:59
INVALID / WONTFIX. closing as not clear what to do here.

**Closed as completed by rufuspollock** 2019-03-20 20:59 UTC
